### ISSUE TITLE
queryStringParameters getting mangled

### ISSUE THREAD

**Issue by jdobyns** [elthrasher/http-lambda-invoker#50]
I am able to call my function with `sam local start-api`

using the following request URI
```
export uri=/reward/?json=%7B%22objects_location%22%3A+%5B%5D%2C+%22objects_left_of_center%22%3A+%5B%5D%2C+%22distance_from_center%22%3A+2.3124996442425605%2C+%22speed%22%3A+1.5%2C+%22waypoints%22%3A+%5B%5B2.909995283569139%2C+0.6831924746239328%5D%2C+%5B3.3199952311658905%2C+0.6833390533713652%5D%2C+%5B3.41999521838461%2C+0.6833748042853732%5D%2C+%5B3.6300023417267235%2C+0.6834498837610459%5D%2C+%5B4.189995119968753%2C+0.6836500863232341%5D%2C+%5B4.500002230529587%2C+0.6837609167129147%5D%2C+%5B4.549995073956144%2C+0.6837787896136626%5D%2C+%5B5.320002125723089%2C+0.6840540742077795%5D%2C+%5B5.420002112941809%2C+0.6840898251217875%5D%2C+%5B5.7800020669292005%2C+0.684218528412216%5D%2C+%5B6.289747858140073%2C+0.6921400142174%5D%2C+%5B6.460906484698166%2C+0.7123063542781353%5D%2C+%5B6.5136980596947165%2C+0.7210294115664316%5D%2C+%5B6.704287871536597%2C+0.799598672280553%5D%2C+%5B6.836281775656231%2C+0.8817004790362547%5D%2C+%5B6.991663362669656%2C+1.0062653214908401%5D%2C+%5B7.1142074641408275%2C+1.1693225137564909%5D%2C+%5B7.165830682349035%2C+1.263426756737598%5D%2C+%5B7.280019741788613%2C+1.7628308313393968%5D%2C+%5B7.272892208655982%2C+1.8132370038722583%5D%2C+%5B7.265960701310593%2C+1.8622568749360433%5D%2C+%5B7.1045747673751585%2C+2.3014874894475916%5D%2C+%5B7.011749008840918%2C+2.419260292916218%5D%2C+%5B6.727273712845888%2C+2.6474924751765463%5D%2C+%5B6.536921216759571%2C+2.7266447610626687%5D%2C+%5B6.079802178702642%2C+2.773360773339069%5D%2C+%5B5.919813651266964%2C+2.772005974951175%5D%2C+%5B5.719827991972368%2C+2.7703124769663074%5D%2C+%5B5.670000926947205%2C+2.7698905365406308%5D%2C+%5B5.200034627604903%2C+2.765910816276192%5D%2C+%5B5.049876033335467%2C+2.7646392587170006%5D%2C+%5B5.002030872389276%2C+2.768980714618128%5D%2C+%5B4.942709994269048%2C+2.775327848322301%5D%2C+%5B4.561340171137485%2C+2.898322513024676%5D%2C+%5B4.258533108743229%2C+3.166955220685885%5D%2C+%5B4.092728535429521%2C+3.3703748558215287%5D%2C+%5B4.001121969780925%2C+3.482763638518189%5D%2C+%5B3.774000078716213%2C+3.761411273431655%5D%2C+%5B3.6823935130676184%2C+3.8738000561283137%5D%2C+%5B3.5490587458571623%2C+4.037383660336441%5D%2C+%5B3.2758532950668884%2C+4.333295323360169%5D%2C+%5B3.1911463583891155%2C+4.385684825652305%5D%2C+%5B3.0954945192403103%2C+4.435922305057415%5D%2C+%5B2.9549738926202442%2C+4.484413606024224%5D%2C+%5B2.8089822299540046%2C+4.500038654567632%5D%2C+%5B2.8110045575773057%2C+4.499832029419236%5D%2C+%5B2.5003276964136627%2C+4.498718163592657%5D%2C+%5B2.249377566090162%2C+4.491428972830993%5D%2C+%5B1.990177178741659%2C+4.483900142037221%5D%2C+%5B1.7395172672798365%2C+4.476619381080485%5D%2C+%5B1.1871156114665855%2C+4.391792930201858%5D%2C+%5B1.1054389398706574%2C+4.3402307341807065%5D%2C+%5B0.7316196323127645%2C+3.819658838269335%5D%2C+%5B0.7080468873794841%2C+3.5295953182618844%5D%2C+%5B0.8747319412102282%2C+2.7251244177375193%5D%2C+%5B0.8863119620897287%2C+2.6692358445815714%5D%2C+%5B0.9180990438541362%2C+2.5158220758940644%5D%2C+%5B0.9380374746317692%2C+2.4195933679559642%5D%2C+%5B1.0212099341560652%2C+2.0181787127447155%5D%2C+%5B1.043063552869095%2C+1.912706746772055%5D%2C+%5B1.0936256517149223%2C+1.6686792454688633%5D%2C+%5B1.219724413480236%2C+1.169889412099395%5D%2C+%5B1.2404620134668318%2C+1.1182110370035536%5D%2C+%5B1.286611404297767%2C+1.0270193376917442%5D%2C+%5B1.3195344250237366%2C+0.9895904728963364%5D%2C+%5B1.3897426105955222%2C+0.9097735962139227%5D%2C+%5B1.4563853812178036%2C+0.8435308547287804%5D%2C+%5B1.4996428710531535%2C+0.8193608401945228%5D%2C+%5B2.0400025449490777%2C+0.6828814442283201%5D%2C+%5B2.7500024542019887%2C+0.6831352757177762%5D%2C+%5B2.909995283569139%2C+0.6831924746239328%5D%5D%2C+%22track_length%22%3A+17.671677230923088%2C+%22objects_distance%22%3A+%5B%5D%2C+%22objects_heading%22%3A+%5B%5D%2C+%22object_in_camera%22%3A+false%2C+%22steering_angle%22%3A+-20.0%2C+%22y%22%3A+5.08329965357544%2C+%22x%22%3A+5.767609767714554%2C+%22is_crashed%22%3A+false%2C+%22heading%22%3A+134.187338161613%2C+%22track_width%22%3A+0.6218312230734625%2C+%22all_wheels_on_track%22%3A+false%2C+%22is_left_of_center%22%3A+false%2C+%22is_offtrack%22%3A+true%2C+%22objects_speed%22%3A+%5B%5D%2C+%22closest_objects%22%3A+%5B0%2C+0%5D%2C+%22steps%22%3A+2.0%2C+%22progress%22%3A+34.78856192380332%2C+%22closest_waypoints%22%3A+%5B26%2C+27%5D%2C+%22is_reversed%22%3A+false%7D
```

Working with sam local
```
curl -v localhost:3000$uri
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /reward/?json=%7B%22objects_location%22%3A+%5B%5D%2C+%22objects_left_of_center%22%3A+%5B%5D%2C+%22distance_from_center%22%3A+2.3124996442425605%2C+%22speed%22%3A+1.5%2C+%22waypoints%22%3A+%5B%5B2.909995283569139%2C+0.6831924746239328%5D%2C+%5B3.3199952311658905%2C+0.6833390533713652%5D%2C+%5B3.41999521838461%2C+0.6833748042853732%5D%2C+%5B3.6300023417267235%2C+0.6834498837610459%5D%2C+%5B4.189995119968753%2C+0.6836500863232341%5D%2C+%5B4.500002230529587%2C+0.6837609167129147%5D%2C+%5B4.549995073956144%2C+0.6837787896136626%5D%2C+%5B5.320002125723089%2C+0.6840540742077795%5D%2C+%5B5.420002112941809%2C+0.6840898251217875%5D%2C+%5B5.7800020669292005%2C+0.684218528412216%5D%2C+%5B6.289747858140073%2C+0.6921400142174%5D%2C+%5B6.460906484698166%2C+0.7123063542781353%5D%2C+%5B6.5136980596947165%2C+0.7210294115664316%5D%2C+%5B6.704287871536597%2C+0.799598672280553%5D%2C+%5B6.836281775656231%2C+0.8817004790362547%5D%2C+%5B6.991663362669656%2C+1.0062653214908401%5D%2C+%5B7.1142074641408275%2C+1.1693225137564909%5D%2C+%5B7.165830682349035%2C+1.263426756737598%5D%2C+%5B7.280019741788613%2C+1.7628308313393968%5D%2C+%5B7.272892208655982%2C+1.8132370038722583%5D%2C+%5B7.265960701310593%2C+1.8622568749360433%5D%2C+%5B7.1045747673751585%2C+2.3014874894475916%5D%2C+%5B7.011749008840918%2C+2.419260292916218%5D%2C+%5B6.727273712845888%2C+2.6474924751765463%5D%2C+%5B6.536921216759571%2C+2.7266447610626687%5D%2C+%5B6.079802178702642%2C+2.773360773339069%5D%2C+%5B5.919813651266964%2C+2.772005974951175%5D%2C+%5B5.719827991972368%2C+2.7703124769663074%5D%2C+%5B5.670000926947205%2C+2.7698905365406308%5D%2C+%5B5.200034627604903%2C+2.765910816276192%5D%2C+%5B5.049876033335467%2C+2.7646392587170006%5D%2C+%5B5.002030872389276%2C+2.768980714618128%5D%2C+%5B4.942709994269048%2C+2.775327848322301%5D%2C+%5B4.561340171137485%2C+2.898322513024676%5D%2C+%5B4.258533108743229%2C+3.166955220685885%5D%2C+%5B4.092728535429521%2C+3.3703748558215287%5D%2C+%5B4.001121969780925%2C+3.482763638518189%5D%2C+%5B3.774000078716213%2C+3.761411273431655%5D%2C+%5B3.6823935130676184%2C+3.8738000561283137%5D%2C+%5B3.5490587458571623%2C+4.037383660336441%5D%2C+%5B3.2758532950668884%2C+4.333295323360169%5D%2C+%5B3.1911463583891155%2C+4.385684825652305%5D%2C+%5B3.0954945192403103%2C+4.435922305057415%5D%2C+%5B2.9549738926202442%2C+4.484413606024224%5D%2C+%5B2.8089822299540046%2C+4.500038654567632%5D%2C+%5B2.8110045575773057%2C+4.499832029419236%5D%2C+%5B2.5003276964136627%2C+4.498718163592657%5D%2C+%5B2.249377566090162%2C+4.491428972830993%5D%2C+%5B1.990177178741659%2C+4.483900142037221%5D%2C+%5B1.7395172672798365%2C+4.476619381080485%5D%2C+%5B1.1871156114665855%2C+4.391792930201858%5D%2C+%5B1.1054389398706574%2C+4.3402307341807065%5D%2C+%5B0.7316196323127645%2C+3.819658838269335%5D%2C+%5B0.7080468873794841%2C+3.5295953182618844%5D%2C+%5B0.8747319412102282%2C+2.7251244177375193%5D%2C+%5B0.8863119620897287%2C+2.6692358445815714%5D%2C+%5B0.9180990438541362%2C+2.5158220758940644%5D%2C+%5B0.9380374746317692%2C+2.4195933679559642%5D%2C+%5B1.0212099341560652%2C+2.0181787127447155%5D%2C+%5B1.043063552869095%2C+1.912706746772055%5D%2C+%5B1.0936256517149223%2C+1.6686792454688633%5D%2C+%5B1.219724413480236%2C+1.169889412099395%5D%2C+%5B1.2404620134668318%2C+1.1182110370035536%5D%2C+%5B1.286611404297767%2C+1.0270193376917442%5D%2C+%5B1.3195344250237366%2C+0.9895904728963364%5D%2C+%5B1.3897426105955222%2C+0.9097735962139227%5D%2C+%5B1.4563853812178036%2C+0.8435308547287804%5D%2C+%5B1.4996428710531535%2C+0.8193608401945228%5D%2C+%5B2.0400025449490777%2C+0.6828814442283201%5D%2C+%5B2.7500024542019887%2C+0.6831352757177762%5D%2C+%5B2.909995283569139%2C+0.6831924746239328%5D%5D%2C+%22track_length%22%3A+17.671677230923088%2C+%22objects_distance%22%3A+%5B%5D%2C+%22objects_heading%22%3A+%5B%5D%2C+%22object_in_camera%22%3A+false%2C+%22steering_angle%22%3A+-20.0%2C+%22y%22%3A+5.08329965357544%2C+%22x%22%3A+5.767609767714554%2C+%22is_crashed%22%3A+false%2C+%22heading%22%3A+134.187338161613%2C+%22track_width%22%3A+0.6218312230734625%2C+%22all_wheels_on_track%22%3A+false%2C+%22is_left_of_center%22%3A+false%2C+%22is_offtrack%22%3A+true%2C+%22objects_speed%22%3A+%5B%5D%2C+%22closest_objects%22%3A+%5B0%2C+0%5D%2C+%22steps%22%3A+2.0%2C+%22progress%22%3A+34.78856192380332%2C+%22closest_waypoints%22%3A+%5B26%2C+27%5D%2C+%22is_reversed%22%3A+false%7D HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.58.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: application/json
< Content-Length: 17
< Server: Werkzeug/1.0.1 Python/3.7.7
< Date: Sun, 14 Jun 2020 07:27:40 GMT
<
* Closing connection 0
{"reward": 2e-26}
```

Not working with http-lambda-invoker

```
curl -v localhost:18080$uri
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 18080 (#0)
> GET /reward/?json=%7B%22objects_location%22%3A+%5B%5D%2C+%22objects_left_of_center%22%3A+%5B%5D%2C+%22distance_from_center%22%3A+2.3124996442425605%2C+%22speed%22%3A+1.5%2C+%22waypoints%22%3A+%5B%5B2.909995283569139%2C+0.6831924746239328%5D%2C+%5B3.3199952311658905%2C+0.6833390533713652%5D%2C+%5B3.41999521838461%2C+0.6833748042853732%5D%2C+%5B3.6300023417267235%2C+0.6834498837610459%5D%2C+%5B4.189995119968753%2C+0.6836500863232341%5D%2C+%5B4.500002230529587%2C+0.6837609167129147%5D%2C+%5B4.549995073956144%2C+0.6837787896136626%5D%2C+%5B5.320002125723089%2C+0.6840540742077795%5D%2C+%5B5.420002112941809%2C+0.6840898251217875%5D%2C+%5B5.7800020669292005%2C+0.684218528412216%5D%2C+%5B6.289747858140073%2C+0.6921400142174%5D%2C+%5B6.460906484698166%2C+0.7123063542781353%5D%2C+%5B6.5136980596947165%2C+0.7210294115664316%5D%2C+%5B6.704287871536597%2C+0.799598672280553%5D%2C+%5B6.836281775656231%2C+0.8817004790362547%5D%2C+%5B6.991663362669656%2C+1.0062653214908401%5D%2C+%5B7.1142074641408275%2C+1.1693225137564909%5D%2C+%5B7.165830682349035%2C+1.263426756737598%5D%2C+%5B7.280019741788613%2C+1.7628308313393968%5D%2C+%5B7.272892208655982%2C+1.8132370038722583%5D%2C+%5B7.265960701310593%2C+1.8622568749360433%5D%2C+%5B7.1045747673751585%2C+2.3014874894475916%5D%2C+%5B7.011749008840918%2C+2.419260292916218%5D%2C+%5B6.727273712845888%2C+2.6474924751765463%5D%2C+%5B6.536921216759571%2C+2.7266447610626687%5D%2C+%5B6.079802178702642%2C+2.773360773339069%5D%2C+%5B5.919813651266964%2C+2.772005974951175%5D%2C+%5B5.719827991972368%2C+2.7703124769663074%5D%2C+%5B5.670000926947205%2C+2.7698905365406308%5D%2C+%5B5.200034627604903%2C+2.765910816276192%5D%2C+%5B5.049876033335467%2C+2.7646392587170006%5D%2C+%5B5.002030872389276%2C+2.768980714618128%5D%2C+%5B4.942709994269048%2C+2.775327848322301%5D%2C+%5B4.561340171137485%2C+2.898322513024676%5D%2C+%5B4.258533108743229%2C+3.166955220685885%5D%2C+%5B4.092728535429521%2C+3.3703748558215287%5D%2C+%5B4.001121969780925%2C+3.482763638518189%5D%2C+%5B3.774000078716213%2C+3.761411273431655%5D%2C+%5B3.6823935130676184%2C+3.8738000561283137%5D%2C+%5B3.5490587458571623%2C+4.037383660336441%5D%2C+%5B3.2758532950668884%2C+4.333295323360169%5D%2C+%5B3.1911463583891155%2C+4.385684825652305%5D%2C+%5B3.0954945192403103%2C+4.435922305057415%5D%2C+%5B2.9549738926202442%2C+4.484413606024224%5D%2C+%5B2.8089822299540046%2C+4.500038654567632%5D%2C+%5B2.8110045575773057%2C+4.499832029419236%5D%2C+%5B2.5003276964136627%2C+4.498718163592657%5D%2C+%5B2.249377566090162%2C+4.491428972830993%5D%2C+%5B1.990177178741659%2C+4.483900142037221%5D%2C+%5B1.7395172672798365%2C+4.476619381080485%5D%2C+%5B1.1871156114665855%2C+4.391792930201858%5D%2C+%5B1.1054389398706574%2C+4.3402307341807065%5D%2C+%5B0.7316196323127645%2C+3.819658838269335%5D%2C+%5B0.7080468873794841%2C+3.5295953182618844%5D%2C+%5B0.8747319412102282%2C+2.7251244177375193%5D%2C+%5B0.8863119620897287%2C+2.6692358445815714%5D%2C+%5B0.9180990438541362%2C+2.5158220758940644%5D%2C+%5B0.9380374746317692%2C+2.4195933679559642%5D%2C+%5B1.0212099341560652%2C+2.0181787127447155%5D%2C+%5B1.043063552869095%2C+1.912706746772055%5D%2C+%5B1.0936256517149223%2C+1.6686792454688633%5D%2C+%5B1.219724413480236%2C+1.169889412099395%5D%2C+%5B1.2404620134668318%2C+1.1182110370035536%5D%2C+%5B1.286611404297767%2C+1.0270193376917442%5D%2C+%5B1.3195344250237366%2C+0.9895904728963364%5D%2C+%5B1.3897426105955222%2C+0.9097735962139227%5D%2C+%5B1.4563853812178036%2C+0.8435308547287804%5D%2C+%5B1.4996428710531535%2C+0.8193608401945228%5D%2C+%5B2.0400025449490777%2C+0.6828814442283201%5D%2C+%5B2.7500024542019887%2C+0.6831352757177762%5D%2C+%5B2.909995283569139%2C+0.6831924746239328%5D%5D%2C+%22track_length%22%3A+17.671677230923088%2C+%22objects_distance%22%3A+%5B%5D%2C+%22objects_heading%22%3A+%5B%5D%2C+%22object_in_camera%22%3A+false%2C+%22steering_angle%22%3A+-20.0%2C+%22y%22%3A+5.08329965357544%2C+%22x%22%3A+5.767609767714554%2C+%22is_crashed%22%3A+false%2C+%22heading%22%3A+134.187338161613%2C+%22track_width%22%3A+0.6218312230734625%2C+%22all_wheels_on_track%22%3A+false%2C+%22is_left_of_center%22%3A+false%2C+%22is_offtrack%22%3A+true%2C+%22objects_speed%22%3A+%5B%5D%2C+%22closest_objects%22%3A+%5B0%2C+0%5D%2C+%22steps%22%3A+2.0%2C+%22progress%22%3A+34.78856192380332%2C+%22closest_waypoints%22%3A+%5B26%2C+27%5D%2C+%22is_reversed%22%3A+false%7D HTTP/1.1
> Host: localhost:18080
> User-Agent: curl/7.58.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

http-lambda-invoker log

```
lambda    | START RequestId: 64fa1225-01aa-14df-6e42-fed7039fac34 Version: $LATEST
lambda    | event: {'body': '', 'headers': {'Accept': '*/*', 'User-Agent': 'curl/7.58.0'}, 'httpMethod': 'GET', 'path': '/reward/', 'queryStringParameters': {'json': ['{"objects_location": [], "objects_left_of_center": [], "distance_from_center": 2.3124996442425605, "speed": 1.5, "waypoints": [[2.909995283569139, 0.6831924746239328], [3.3199952311658905, 0.6833390533713652], [3.41999521838461, 0.6833748042853732], [3.6300023417267235, 0.6834498837610459], [4.189995119968753, 0.6836500863232341], [4.500002230529587, 0.6837609167129147], [4.549995073956144, 0.6837787896136626], [5.320002125723089, 0.6840540742077795], [5.420002112941809, 0.6840898251217875], [5.7800020669292005, 0.684218528412216], [6.289747858140073, 0.6921400142174], [6.460906484698166, 0.7123063542781353], [6.5136980596947165, 0.7210294115664316], [6.704287871536597, 0.799598672280553], [6.836281775656231, 0.8817004790362547], [6.991663362669656, 1.0062653214908401], [7.1142074641408275, 1.1693225137564909], [7.165830682349035, 1.263426756737598], [7.280019741788613, 1.7628308313393968], [7.272892208655982, 1.8132370038722583], [7.265960701310593, 1.8622568749360433], [7.1045747673751585, 2.3014874894475916], [7.011749008840918, 2.419260292916218], [6.727273712845888, 2.6474924751765463], [6.536921216759571, 2.7266447610626687], [6.079802178702642, 2.773360773339069], [5.919813651266964, 2.772005974951175], [5.719827991972368, 2.7703124769663074], [5.670000926947205, 2.7698905365406308], [5.200034627604903, 2.765910816276192], [5.049876033335467, 2.7646392587170006], [5.002030872389276, 2.768980714618128], [4.942709994269048, 2.775327848322301], [4.561340171137485, 2.898322513024676], [4.258533108743229, 3.166955220685885], [4.092728535429521, 3.3703748558215287], [4.001121969780925, 3.482763638518189], [3.774000078716213, 3.761411273431655], [3.6823935130676184, 3.8738000561283137], [3.5490587458571623, 4.037383660336441], [3.2758532950668884, 4.333295323360169], [3.1911463583891155, 4.385684825652305], [3.0954945192403103, 4.435922305057415], [2.9549738926202442, 4.484413606024224], [2.8089822299540046, 4.500038654567632], [2.8110045575773057, 4.499832029419236], [2.5003276964136627, 4.498718163592657], [2.249377566090162, 4.491428972830993], [1.990177178741659, 4.483900142037221], [1.7395172672798365, 4.476619381080485], [1.1871156114665855, 4.391792930201858], [1.1054389398706574, 4.3402307341807065], [0.7316196323127645, 3.819658838269335], [0.7080468873794841, 3.5295953182618844], [0.8747319412102282, 2.7251244177375193], [0.8863119620897287, 2.6692358445815714], [0.9180990438541362, 2.5158220758940644], [0.9380374746317692, 2.4195933679559642], [1.0212099341560652, 2.0181787127447155], [1.043063552869095, 1.912706746772055], [1.0936256517149223, 1.6686792454688633], [1.219724413480236, 1.169889412099395], [1.2404620134668318, 1.1182110370035536], [1.286611404297767, 1.0270193376917442], [1.3195344250237366, 0.9895904728963364], [1.3897426105955222, 0.9097735962139227], [1.4563853812178036, 0.8435308547287804], [1.4996428710531535, 0.8193608401945228], [2.0400025449490777, 0.6828814442283201], [2.7500024542019887, 0.6831352757177762], [2.909995283569139, 0.6831924746239328]], "track_length": 17.671677230923088, "objects_distance": [], "objects_heading": [], "object_in_camera": false, "steering_angle": -20.0, "y": 5.08329965357544, "x": 5.767609767714554, "is_crashed": false, "heading": 134.187338161613, "track_width": 0.6218312230734625, "all_wheels_on_track": false, "is_left_of_center": false, "is_offtrack": true, "objects_speed": [], "closest_objects": [0, 0], "steps": 2.0, "progress": 34.78856192380332, "closest_waypoints": [26, 27], "is_reversed": false}']}}
lambda    | [ERROR] TypeError: the JSON object must be str, bytes or bytearray, not list
lambda    | Traceback (most recent call last):
lambda    |   File "/var/task/app.py", line 29, in lambda_handler
lambda    |     params = json.loads(event["queryStringParameters"]["json"])
lambda    |   File "/var/lang/lib/python3.7/json/__init__.py", line 341, in loads
lambda    |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
lambda    | 2020/06/14 07:32:23 Setting Reply in handleErrorRequest
lambda    | 2020/06/14 07:32:23 &{TypeError the JSON object must be str, bytes or bytearray, not list [0xc00034b220 0xc00034b230] <nil>}
lambda    | 2020/06/14 07:32:23 In /invocation/next
lambda    | 2020/06/14 07:32:23 Reply is not nil
lambda    | 2020/06/14 07:32:23 EndInvoke()
lambda    | END RequestId: 64fa1225-01aa-14df-6e42-fed7039fac34
lambda    | REPORT RequestId: 64fa1225-01aa-14df-6e42-fed7039fac34	Duration: 7.55 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 107 MB
```

I'm sure I've done something wrong, can you help ?

**Comment by elthrasher** [comment]
@jdobyns So sorry for not getting back to you. I honestly didn't know that I don't automatically get notified of new issues. Have you come up with any solution or workaround? I can give this a look if not.

**Comment by bence-nagy** [comment]
I am almost sure that this problem is caused by this line:

https://github.com/elthrasher/http-lambda-invoker/blob/master/http-lambda-invoker.go#L146

The `Fprintf` method will treat special url-encoded parts of your response as formatting parameters. Like "%2F'", which encodes a "/", will be used as a floating point formatter sting. (See https://golang.org/pkg/fmt/#Fprintf)

I think simply switching that line to `fmt.Fprint(w, string(response.Body))` would solve this issue.

**Comment by douglas-gibbons-lark** [comment]
PR is merged. Can we close this issue?
